msrv = "1.94.0"

avoid-breaking-exported-api = false
check-private-items = true
warn-on-all-wildcard-imports = true

allow-dbg-in-tests = false
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-print-in-tests = true
allow-unwrap-in-tests = true
