//! Host-side embedding of the stablecoin RISC Zero guest ELF.
//!
//! Re-exports the constants produced by `build.rs` via `risc0_build::embed_methods` —
//! `STABLECOIN_ELF`, `STABLECOIN_PATH`, and `STABLECOIN_ID` — used by host code to
//! load and identify the guest binary.

#![allow(
    missing_docs,
    reason = "constants below are generated by risc0_build::embed_methods at build time"
)]

include!(concat!(env!("OUT_DIR"), "/methods.rs"));
